export const reputation: Readonly<string[][]> = [
  [" ", ""],
  ["Rank 1", ""],
  ["Rank 2", ""],
  ["Rank 3", ""],
  ["Rank 4", ""],
  ["Rank 1", ""],
  ["Neutral", "hover:bg-slate-100/5"],
  ["Accepted", "bg-emerald-900/20 hover:bg-emerald-900/30"],
  ["Liked", "bg-emerald-900/40 hover:bg-emerald-900/50"],
  ["Idolized", "bg-emerald-900/60 hover:bg-emerald-900/70"],
  ["Rank 2", ""],
  ["Shunned", "bg-red-900/20 hover:bg-red-900/30"],
  ["Mixed", "hover:bg-slate-100/5"],
  ["Smiling Troublemaker", "bg-emerald-900/20 hover:bg-emerald-900/30"],
  ["Good-Natued Rascal", "bg-emerald-900/40 hover:bg-emerald-900/50"],
  ["Rank 3", ""],
  ["Hated", "bg-red-900/40 hover:bg-red-900/50"],
  ["Sneering Punk", "bg-red-900/20 bg-red-900/30"],
  ["Unpredictable", "hover:bg-slate-100/5"],
  ["Dark Hero", "bg-emerald-900/20 hover:bg-emerald-900/30"],
  ["Rank 4", ""],
  ["Vilified", "bg-red-900/60 hover:bg-red-900/70"],
  ["Merciful Thug", "bg-red-900/40 hover:bg-red-900/50"],
  ["Soft-Hearted Devil", "bg-red-900/20 hover:bg-red-900/30"],
  ["Wild Child", "hover:bg-slate-100/5"],
];

// const factions: Set<{ unaligned: boolean; name: string; nickname: string }> =
//   new Set([
//     { unaligned: true, name: "Angels", nickname: "Angels" },
//     { unaligned: true, name: "Aztecas", nickname: "Aztecas" },
//     { unaligned: true, name: "Bondi Boys MC", nickname: "BBMC" },
//     { unaligned: true, name: "Brouge Street Kingz", nickname: "B$K" },
//     { unaligned: true, name: "Cerebus", nickname: "Cerebus" },
//     { unaligned: true, name: "Chang Gang", nickname: "CG" },
//     { unaligned: true, name: "Cleanbois", nickname: "CB" },
//     { unaligned: true, name: "Eastside Vagos", nickname: "ESV" },
//     { unaligned: true, name: "Grove Street Ballas", nickname: "GSB" },
//     { unaligned: true, name: "Gulag Gang", nickname: "GG" },
//     { unaligned: true, name: "Hogs of Anarchy", nickname: "HOA" },
//     { unaligned: true, name: "Hydra", nickname: "Hydra" },
//     {
//       unaligned: true,
//       name: "Los Santos Policee Department",
//       nickname: "LSPD",
//     },
//     { unaligned: true, name: "Lost MC", nickname: "Lost" },
//     { unaligned: true, name: "Marabunta Grande", nickname: "MG" },
//     { unaligned: true, name: "Mayhem", nickname: "Mayhem" },
//     { unaligned: true, name: "Mortelle", nickname: "Mortelle" },
//     { unaligned: true, name: "Natural Born Crackheads", nickname: "NBC" },
//     { unaligned: true, name: "Paleto Bay Sheriff's Office", nickname: "PBSO" },
//     { unaligned: true, name: "Rangers", nickname: "Rangers" },
//     {
//       unaligned: true,
//       name: "Ray's Unfortunate Scuff Team",
//       nickname: "R.U.S.T",
//     },
//     {
//       unaligned: true,
//       name: "Senora Desert Sheriff's Office",
//       nickname: "SDSO",
//     },
//     { unaligned: true, name: "Seaside", nickname: "SS" },
//     { unaligned: true, name: "Sessanta Nove", nickname: "69" },
//     { unaligned: true, name: "Street Team", nickname: "ST" },
//     { unaligned: true, name: "The Clowns", nickname: "Clowns" },
//     { unaligned: true, name: "The Dons", nickname: "Dons" },
//     { unaligned: true, name: "The Families", nickname: "GSF" },
//     { unaligned: true, name: "The Guild", nickname: "Nerds" },
//     { unaligned: true, name: "The Hidden", nickname: "Hidden" },
//     { unaligned: true, name: "The Mandem", nickname: "MDM" },
//     { unaligned: true, name: "The Saints", nickname: "Saints" },
//     { unaligned: true, name: "Troopers", nickname: "Troopers" },
//     { unaligned: true, name: "Wastelanders", nickname: "WL" },
//   ]);
